### ISSUE TITLE
Migrate to MavenCentral

### ISSUE THREAD

**Issue by Goooler** [patrykmichalik/opto#2]
See https://github.com/jitpack/jitpack.io/issues/5213, something wrong with jitpack, if we can migrate to `MavenCentral`?

**Comment by patrykmichalik** [comment]
Hello! I’ll be publishing Opto to the Central Repository shortly. I’ll let you know once it’s available there.

**Comment by Goooler** [comment]
Thanks! After that, we can remove `jitpack` maven repo in Lawnchair.

**Comment by patrykmichalik** [comment]
As of version 1.0.15, Opto is available in the Central Repository.

```
dependencies {
    ...
    implementation "com.patrykmichalik.opto:domain:1.0.15"
    implementation "com.patrykmichalik.opto:core:1.0.15"
    implementation "com.patrykmichalik.opto:compose:1.0.15"
}
```

Should you face any issues, please feel free to let me know.

**Comment by Goooler** [comment]
thanks
